name: Deploy to prod

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy -t prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DB_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod

      