name: Deploy to dev

on:
  workflow_dispatch:

  push:
    branches:
      - dev
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy -t dev
        env:
          DATABRICKS_TOKEN: ${{ secrets.DB_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

      - run: databricks bundle run feature_store_etl -t dev
        env:
            DATABRICKS_TOKEN: ${{ secrets.DB_TOKEN }}
            DATABRICKS_BUNDLE_ENV: dev